
#ifndef MTLC_MEMORY_H
#define MTLC_MEMORY_H

#ifdef __cplusplus
extern "C" {
#endif

typedef enum {
  MTLC_ADDRESS_SPACE_DEFAULT = 0,
  MTLC_ADDRESS_SPACE_GENERIC,
  MTLC_ADDRESS_SPACE_GLOBAL,
  MTLC_ADDRESS_SPACE_WORKGROUP,
  MTLC_ADDRESS_SPACE_CONSTANT,
  MTLC_ADDRESS_SPACE_PRIVATE
} MtlcAddressSpace;

typedef enum {
  MTLC_VIEW_LAYOUT_NONE = 0,
  MTLC_VIEW_LAYOUT_ROW,
  MTLC_VIEW_LAYOUT_COL,
  MTLC_VIEW_LAYOUT_SWIZZLE32,
  MTLC_VIEW_LAYOUT_SWIZZLE64,
  MTLC_VIEW_LAYOUT_SWIZZLE128,
  MTLC_VIEW_LAYOUT_INTERLEAVE,
  MTLC_VIEW_LAYOUT_FRAGMENT_A,
  MTLC_VIEW_LAYOUT_FRAGMENT_B,
  MTLC_VIEW_LAYOUT_FRAGMENT_C
} MtlcViewLayout;

typedef enum {
  MTLC_MEMORY_ORDER_DEFAULT = 0,
  MTLC_MEMORY_ORDER_RELAXED,
  MTLC_MEMORY_ORDER_ACQUIRE,
  MTLC_MEMORY_ORDER_RELEASE,
  MTLC_MEMORY_ORDER_ACQ_REL,
  MTLC_MEMORY_ORDER_SEQ_CST
} MtlcMemoryOrder;

typedef enum {
  MTLC_MEMORY_SCOPE_DEFAULT = 0,
  MTLC_MEMORY_SCOPE_WORK_ITEM,
  MTLC_MEMORY_SCOPE_SUBGROUP,
  MTLC_MEMORY_SCOPE_WORKGROUP,
  MTLC_MEMORY_SCOPE_DEVICE,
  MTLC_MEMORY_SCOPE_SYSTEM
} MtlcMemoryScope;

typedef enum {
  MTLC_MEMORY_REGION_NONE = 0,
  MTLC_MEMORY_REGION_WORKGROUP = 1u << 0,
  MTLC_MEMORY_REGION_GLOBAL = 1u << 1
} MtlcMemoryRegion;

typedef enum {
  MTLC_ASYNC_CACHE_DEFAULT = 0,
  MTLC_ASYNC_CACHE_ALL,
  MTLC_ASYNC_CACHE_GLOBAL
} MtlcAsyncCache;

#ifdef __cplusplus
}
#endif

#endif
