; Generated by MethASM
; x86-64 Assembly Output

section .text
; Code section

; First pass: processing 2 declarations
; Declaration 0 type: 3 (AST_INLINE_ASM = 15)
; Declaration 1 type: 2 (AST_INLINE_ASM = 15)
    ; Struct declaration: Vector3
    ; Struct Vector3: size=12, alignment=4

global main

main:
    push rbp        ; Save old base pointer
    mov rbp, rsp  ; Set new base pointer
    ; Save callee-saved registers
    push rbx         ; Save callee-saved register
    push r12         ; Save callee-saved register
    push r13         ; Save callee-saved register
    push r14         ; Save callee-saved register
    push r15         ; Save callee-saved register
    sub rsp, 16    ; Allocate 16 bytes on stack (aligned)
    ; Zero-initialize local variable space
    mov rdi, rsp  ; Destination for memset
    mov rax, 0     ; Value to set (zero)
    mov rcx, 16    ; Number of bytes
    rep stosb         ; Zero-fill the stack space
    ; Registering 0 function parameters
    ; Added 8 bytes padding for 16-byte alignment
    ; Local variable: v1 (Vector3*, 8 bytes) at offset -8
    ; Initialize variable v1
    ; Heap allocation: new Vector3
    mov rdi, 12      ; size in bytes
    extern gc_alloc
    call gc_alloc
    mov [rbp - 8], rax     ; Store int64
    ; Integer literal: 10
    mov rax, 10
    push rax           ; Save assigned value
    ; Load variable: v1
    mov rax, [rbp - 8]  ; From stack [rbp - 8]
    pop rcx            ; Restore value
    mov dword [rax], ecx
    ; Integer literal: 20
    mov rax, 20
    push rax           ; Save assigned value
    ; Load variable: v1
    mov rax, [rbp - 8]  ; From stack [rbp - 8]
    add rax, 4       ; Field address
    pop rcx            ; Restore value
    mov dword [rax], ecx
    ; Added 8 bytes padding for 16-byte alignment
    ; Local variable: v2 (Vector3*, 8 bytes) at offset -24
    ; Initialize variable v2
    ; Heap allocation: new Vector3
    mov rdi, 12      ; size in bytes
    extern gc_alloc
    call gc_alloc
    mov [rbp - 24], rax     ; Store int64
    ; Integer literal: 30
    mov rax, 30
    push rax           ; Save assigned value
    ; Load variable: v2
    mov rax, [rbp - 24]  ; From stack [rbp - 24]
    add rax, 8       ; Field address
    pop rcx            ; Restore value
    mov dword [rax], ecx
    ; Return statement
    ; Binary operation: +
    ; Binary operation: +
    ; Load variable: v1
    mov rax, [rbp - 8]  ; From stack [rbp - 8]
    mov eax, dword [rax]
    push rax           ; Save left operand
    ; Load variable: v1
    mov rax, [rbp - 8]  ; From stack [rbp - 8]
    add rax, 4       ; Field address
    mov eax, dword [rax]
    mov rbx, rax     ; Move right operand to RBX
    pop rax            ; Restore left operand
    add rax, rbx      ; + operation
    push rax           ; Save left operand
    ; Load variable: v2
    mov rax, [rbp - 24]  ; From stack [rbp - 24]
    add rax, 8       ; Field address
    mov eax, dword [rax]
    mov rbx, rax     ; Move right operand to RBX
    pop rax            ; Restore left operand
    add rax, rbx      ; + operation
    ; Return value in rax
    jmp Lmain_exit
Lmain_exit:
    ; Function epilogue
    mov rsp, rbp  ; Restore stack pointer
    ; Restore callee-saved registers
    pop r15          ; Restore callee-saved register
    pop r14          ; Restore callee-saved register
    pop r13          ; Restore callee-saved register
    pop r12          ; Restore callee-saved register
    pop rbx          ; Restore callee-saved register
    pop rbp         ; Restore old base pointer
    ret               ; Return to caller

; Default program entry point
global _start
_start:
    ; Initialize garbage collector runtime
    mov rdi, rsp
    extern gc_init
    call gc_init
    ; Call user main function
    call main
    push rax         ; Preserve main return code
    extern gc_shutdown
    call gc_shutdown
    pop rdi          ; Use main return as exit code
    mov rax, 60    ; sys_exit
    syscall
