; Generated by MethASM
; x86-64 Assembly Output

section .text
; Code section

; First pass: processing 1 declarations
; Declaration 0 type: 3 (AST_INLINE_ASM = 10)
    ; Struct declaration: Vector3
    ; Struct Vector3: size=4, alignment=4

; Default program entry point
global _start
_start:
    ; Exit gracefully
    mov rax, 60    ; sys_exit
    mov rdi, 0     ; exit status
    syscall
