; Generated by MethASM
; x86-64 Assembly Output

section .text
; Code section

; First pass: processing 3 declarations
; Declaration 0 type: 2 (AST_INLINE_ASM = 15)
; Declaration 1 type: 2 (AST_INLINE_ASM = 15)
; Declaration 2 type: 2 (AST_INLINE_ASM = 15)

global add

add:
    push rbp        ; Save old base pointer
    mov rbp, rsp  ; Set new base pointer
    ; Save callee-saved registers
    push rbx         ; Save callee-saved register
    push r12         ; Save callee-saved register
    push r13         ; Save callee-saved register
    push r14         ; Save callee-saved register
    push r15         ; Save callee-saved register
    ; Registering 2 function parameters
    ; Parameter 'a' in register rcx
    ; Parameter 'b' in register rdx
Ladd_exit:
    ; Function epilogue
    mov rsp, rbp  ; Restore stack pointer
    ; Restore callee-saved registers
    pop r15          ; Restore callee-saved register
    pop r14          ; Restore callee-saved register
    pop r13          ; Restore callee-saved register
    pop r12          ; Restore callee-saved register
    pop rbx          ; Restore callee-saved register
    pop rbp         ; Restore old base pointer
    ret               ; Return to caller

global add

add:
    push rbp        ; Save old base pointer
    mov rbp, rsp  ; Set new base pointer
    ; Save callee-saved registers
    push rbx         ; Save callee-saved register
    push r12         ; Save callee-saved register
    push r13         ; Save callee-saved register
    push r14         ; Save callee-saved register
    push r15         ; Save callee-saved register
    ; Registering 2 function parameters
    ; Parameter 'a' in register rcx
    ; Parameter 'b' in register rdx
    ; Return statement
    ; Binary operation: +
    ; Load variable: a
    mov rax, rcx      ; From register
    push rax           ; Save left operand
    ; Load variable: b
    mov rax, rdx      ; From register
    mov rbx, rax     ; Move right operand to RBX
    pop rax            ; Restore left operand
    add rax, rbx      ; + operation
    ; Return value in rax
    jmp Ladd_exit
Ladd_exit:
    ; Function epilogue
    mov rsp, rbp  ; Restore stack pointer
    ; Restore callee-saved registers
    pop r15          ; Restore callee-saved register
    pop r14          ; Restore callee-saved register
    pop r13          ; Restore callee-saved register
    pop r12          ; Restore callee-saved register
    pop rbx          ; Restore callee-saved register
    pop rbp         ; Restore old base pointer
    ret               ; Return to caller

global main

main:
    push rbp        ; Save old base pointer
    mov rbp, rsp  ; Set new base pointer
    ; Save callee-saved registers
    push rbx         ; Save callee-saved register
    push r12         ; Save callee-saved register
    push r13         ; Save callee-saved register
    push r14         ; Save callee-saved register
    push r15         ; Save callee-saved register
    ; Registering 0 function parameters
    ; Return statement
    ; Function call: add
    sub rsp, 32      ; Allocate shadow space
    sub rsp, 8       ; Align stack to 16 bytes
    ; Save caller-saved registers (selective)
    push rax
    push r10
    push r11
    sub rsp, 16
    movdqu [rsp], xmm4  ; Save XMM4
    sub rsp, 16
    movdqu [rsp], xmm5  ; Save XMM5
    sub rsp, 16
    movdqu [rsp], xmm6  ; Save XMM6
    sub rsp, 16
    movdqu [rsp], xmm7  ; Save XMM7
    ; Passing 2 parameters
    ; Integer literal: 2
    mov rax, 2
    mov ecx, eax    ; Integer parameter 1 in register
    ; Integer literal: 3
    mov rax, 3
    mov edx, eax    ; Integer parameter 2 in register
    call add
    add rsp, 32      ; Clean up shadow space
    ; Stack cleanup complete
    ; Integer/pointer return value in rax
    ; 32-bit return value already in eax
    ; Restore caller-saved registers (selective)
    movdqu xmm7, [rsp]  ; Restore XMM7
    add rsp, 16
    movdqu xmm6, [rsp]  ; Restore XMM6
    add rsp, 16
    movdqu xmm5, [rsp]  ; Restore XMM5
    add rsp, 16
    movdqu xmm4, [rsp]  ; Restore XMM4
    add rsp, 16
    pop r11
    pop r10
    pop rax
    ; Return value in rax (integer/pointer)
    ; Return value in rax
    jmp Lmain_exit
Lmain_exit:
    ; Function epilogue
    mov rsp, rbp  ; Restore stack pointer
    ; Restore callee-saved registers
    pop r15          ; Restore callee-saved register
    pop r14          ; Restore callee-saved register
    pop r13          ; Restore callee-saved register
    pop r12          ; Restore callee-saved register
    pop rbx          ; Restore callee-saved register
    pop rbp         ; Restore old base pointer
    ret               ; Return to caller

; Default program entry point
global _start
_start:
    ; Initialize garbage collector runtime
    mov rdi, rsp
    extern gc_init
    call gc_init
    ; Call user main function
    call main
    push rax         ; Preserve main return code
    extern gc_shutdown
    call gc_shutdown
    pop rdi          ; Use main return as exit code
    mov rax, 60    ; sys_exit
    syscall
