; Generated by MethASM
; x86-64 Assembly Output

section .text
; Code section

; First pass: processing 2 declarations
; Declaration 0 type: 3 (AST_INLINE_ASM = 15)
; Declaration 1 type: 2 (AST_INLINE_ASM = 15)
    ; Struct declaration: Vector3
    ; Struct Vector3: size=12, alignment=4

global main

main:
    push rbp        ; Save old base pointer
    mov rbp, rsp  ; Set new base pointer
    ; Save callee-saved registers
    push rbx         ; Save callee-saved register
    push r12         ; Save callee-saved register
    push r13         ; Save callee-saved register
    push r14         ; Save callee-saved register
    push r15         ; Save callee-saved register
    sub rsp, 32    ; Allocate 32 bytes on stack (aligned)
    ; Zero-initialize local variable space
    mov rdi, rsp  ; Destination for memset
    mov rax, 0     ; Value to set (zero)
    mov rcx, 32    ; Number of bytes
    rep stosb         ; Zero-fill the stack space
    ; Registering 0 function parameters
    ; Added 4 bytes padding for 16-byte alignment
    ; Local variable: v1 (Vector3, 12 bytes) at offset -12
    ; Initialize variable v1
    ; Heap allocation: new Vector3
    mov rdi, 12      ; size in bytes
    extern gc_alloc
    call gc_alloc
    mov [rbp - 12], rax     ; Store int64
    ; Field assignment: .x = ...
    ; Integer literal: 10
    mov rax, 10
    push rax           ; Save value
    ; Load variable: v1
    mov rax, [rbp - 12]  ; From stack [rbp - 12]
    pop rcx            ; Restore value
    mov [rax], rcx     ; Store value to field
    ; Field assignment: .y = ...
    ; Integer literal: 20
    mov rax, 20
    push rax           ; Save value
    ; Load variable: v1
    mov rax, [rbp - 12]  ; From stack [rbp - 12]
    add rax, 4       ; Add field offset
    pop rcx            ; Restore value
    mov [rax], rcx     ; Store value to field
    ; Added 4 bytes padding for 16-byte alignment
    ; Local variable: v2 (Vector3, 12 bytes) at offset -28
    ; Initialize variable v2
    ; Heap allocation: new Vector3
    mov rdi, 12      ; size in bytes
    extern gc_alloc
    call gc_alloc
    mov [rbp - 28], rax     ; Store int64
    ; Field assignment: .z = ...
    ; Integer literal: 30
    mov rax, 30
    push rax           ; Save value
    ; Load variable: v2
    mov rax, [rbp - 28]  ; From stack [rbp - 28]
    add rax, 8       ; Add field offset
    pop rcx            ; Restore value
    mov [rax], rcx     ; Store value to field
    ; Return statement
    ; Binary operation: +
    ; Binary operation: +
    ; Member access: .x
    ; Load variable: v1
    mov rax, [rbp - 12]  ; From stack [rbp - 12]
    ; Field offset for x: 0
    mov rax, [rax]    ; Load field value
    push rax           ; Save left operand
    ; Member access: .y
    ; Load variable: v1
    mov rax, [rbp - 12]  ; From stack [rbp - 12]
    ; Field offset for y: 4
    add rax, 4       ; Add field offset
    mov rax, [rax]    ; Load field value
    mov rbx, rax     ; Move right operand to RBX
    pop rax            ; Restore left operand
    add rax, rbx      ; + operation
    push rax           ; Save left operand
    ; Member access: .z
    ; Load variable: v2
    mov rax, [rbp - 28]  ; From stack [rbp - 28]
    ; Field offset for z: 8
    add rax, 8       ; Add field offset
    mov rax, [rax]    ; Load field value
    mov rbx, rax     ; Move right operand to RBX
    pop rax            ; Restore left operand
    add rax, rbx      ; + operation
    ; Return value in rax
    jmp Lmain_exit
Lmain_exit:
    ; Function epilogue
    mov rsp, rbp  ; Restore stack pointer
    ; Restore callee-saved registers
    pop r15          ; Restore callee-saved register
    pop r14          ; Restore callee-saved register
    pop r13          ; Restore callee-saved register
    pop r12          ; Restore callee-saved register
    pop rbx          ; Restore callee-saved register
    pop rbp         ; Restore old base pointer
    ret               ; Return to caller

; Default program entry point
global _start
_start:
    ; Initialize garbage collector runtime
    mov rdi, rsp
    extern gc_init
    call gc_init
    ; Call user main function
    call main
    push rax         ; Preserve main return code
    extern gc_shutdown
    call gc_shutdown
    pop rdi          ; Use main return as exit code
    mov rax, 60    ; sys_exit
    syscall
