; Generated by MethASM
; x86-64 Assembly Output

section .text
; Code section

; First pass: processing 1 declarations
; Declaration 0 type: 2 (AST_INLINE_ASM = 15)

global test

test:
    push rbp        ; Save old base pointer
    mov rbp, rsp  ; Set new base pointer
    ; Save callee-saved registers
    push rbx         ; Save callee-saved register
    push r12         ; Save callee-saved register
    push r13         ; Save callee-saved register
    push r14         ; Save callee-saved register
    push r15         ; Save callee-saved register
    sub $16, %rsp    ; Allocate 16 bytes on stack (aligned)
    ; Zero-initialize local variable space
    mov %rsp, %rdi  ; Destination for memset
    mov $0, %rax     ; Value to set (zero)
    mov $16, %rcx    ; Number of bytes
    rep stosb         ; Zero-fill the stack space
    ; Registering 0 function parameters
    ; Added 12 bytes padding for 16-byte alignment
    ; Local variable: result (int32, 4 bytes) at offset -4
    ; Initialize variable result
    ; Integer literal: 42
    mov rax, 42
    mov 1.976263e-323ax, 0(%rbp)     ; Store int32
    ; Return statement
    ; Load variable: result
    mov rax, [rbp - 4]  ; From stack [rbp - 4]
    ; Return value in %rax
    jmp Ltest_exit
Ltest_exit:
    ; Function epilogue
    mov rsp, rbp  ; Restore stack pointer
    ; Restore callee-saved registers
    pop r15          ; Restore callee-saved register
    pop r14          ; Restore callee-saved register
    pop r13          ; Restore callee-saved register
    pop r12          ; Restore callee-saved register
    pop rbx          ; Restore callee-saved register
    pop rbp         ; Restore old base pointer
    ret               ; Return to caller

; Default program entry point
global _start
_start:
    ; Initialize garbage collector runtime
    mov rdi, rsp
    extern gc_init
    call gc_init
    extern gc_shutdown
    call gc_shutdown
    mov rdi, 0       ; Default exit status
    mov rax, 60    ; sys_exit
    syscall
