; Generated by MethASM
; x86-64 Assembly Output

section .text
; Code section

; First pass: processing 2 declarations
; Declaration 0 type: 1 (AST_INLINE_ASM = 10)
; Declaration 1 type: 2 (AST_INLINE_ASM = 10)

; Data section for global variables
section .data
; Global variable: g (int32, 4 bytes)
g:
    dd 1


global main

main:
    push rbp        ; Save old base pointer
    mov rbp, rsp  ; Set new base pointer
    ; Save callee-saved registers
    push rbx         ; Save callee-saved register
    push r12         ; Save callee-saved register
    push r13         ; Save callee-saved register
    push r14         ; Save callee-saved register
    push r15         ; Save callee-saved register
    ; Registering 0 function parameters
    ; Return statement
    ; Load variable: g
    mov rax, [g + rip]  ; From global memory
    ; Return value in %rax
    jmp Lmain_exit
Lmain_exit:
    ; Function epilogue
    mov rsp, rbp  ; Restore stack pointer
    ; Restore callee-saved registers
    pop r15          ; Restore callee-saved register
    pop r14          ; Restore callee-saved register
    pop r13          ; Restore callee-saved register
    pop r12          ; Restore callee-saved register
    pop rbx          ; Restore callee-saved register
    pop rbp         ; Restore old base pointer
    ret               ; Return to caller

; Default program entry point
global _start
_start:
    ; Initialize garbage collector runtime
    mov rdi, rsp
    extern gc_init
    call gc_init
    ; Call user main function
    call main
    push rax         ; Preserve main return code
    extern gc_shutdown
    call gc_shutdown
    pop rdi          ; Use main return as exit code
    mov rax, 60    ; sys_exit
    syscall
