; Generated by MethASM
; x86-64 Assembly Output

section .text
; Code section

; First pass: processing 2 declarations
; Declaration 0 type: 3 (AST_INLINE_ASM = 10)
; Declaration 1 type: 2 (AST_INLINE_ASM = 10)
    ; Struct declaration: Vector3
    ; Struct Vector3: size=12, alignment=4

global main

main:
    push rbp        ; Save old base pointer
    mov rbp, rsp  ; Set new base pointer
    ; Save callee-saved registers
    push rbx         ; Save callee-saved register
    push r12         ; Save callee-saved register
    push r13         ; Save callee-saved register
    push r14         ; Save callee-saved register
    push r15         ; Save callee-saved register
    sub $16, %rsp    ; Allocate 16 bytes on stack (aligned)
    ; Zero-initialize local variable space
    mov %rsp, %rdi  ; Destination for memset
    mov $0, %rax     ; Value to set (zero)
    mov $16, %rcx    ; Number of bytes
    rep stosb         ; Zero-fill the stack space
    ; Initialize Garbage Collector
    mov rdi, rbp
    extern gc_init
    call gc_init

    ; Registering 0 function parameters
    ; Added 8 bytes padding for 16-byte alignment
    ; Local variable: v1 (unknown, 8 bytes) at offset -8
    ; Field assignment: .x = ...
    ; Integer literal: 10
    mov rax, 10
    push rax           ; Save value
    ; Load variable: v1
    ; Warning: Variable v1 not found in symbol table
    mov rax, 0        ; Default to 0
    ; Warning: Could not determine field offset for x
    pop rcx            ; Restore value
    mov [rax], rcx     ; Store value to field
    ; Field assignment: .y = ...
    ; Integer literal: 20
    mov rax, 20
    push rax           ; Save value
    ; Load variable: v1
    ; Warning: Variable v1 not found in symbol table
    mov rax, 0        ; Default to 0
    ; Warning: Could not determine field offset for y
    add rax, 8       ; Add field offset
    pop rcx            ; Restore value
    mov [rax], rcx     ; Store value to field
    ; Added 8 bytes padding for 16-byte alignment
    ; Local variable: v2 (unknown, 8 bytes) at offset -24
    ; Field assignment: .z = ...
    ; Integer literal: 30
    mov rax, 30
    push rax           ; Save value
    ; Load variable: v2
    ; Warning: Variable v2 not found in symbol table
    mov rax, 0        ; Default to 0
    ; Warning: Could not determine field offset for z
    add rax, 16       ; Add field offset
    pop rcx            ; Restore value
    mov [rax], rcx     ; Store value to field
    ; Return statement
    ; Binary operation: +
    ; Binary operation: +
    ; Member access: .x
    ; Load variable: v1
    ; Warning: Variable v1 not found in symbol table
    mov rax, 0        ; Default to 0
    ; Warning: Could not determine field offset for x
    ; Field offset for x: 0
    mov rax, [rax]    ; Load field value
    push rax           ; Save left operand
    ; Member access: .y
    ; Load variable: v1
    ; Warning: Variable v1 not found in symbol table
    mov rax, 0        ; Default to 0
    ; Warning: Could not determine field offset for y
    ; Field offset for y: 8
    add rax, 8       ; Add field offset
    mov rax, [rax]    ; Load field value
    mov rbx, rax     ; Move right operand to RBX
    pop rax            ; Restore left operand
    add rax, rbx      ; + operation
    push rax           ; Save left operand
    ; Member access: .z
    ; Load variable: v2
    ; Warning: Variable v2 not found in symbol table
    mov rax, 0        ; Default to 0
    ; Warning: Could not determine field offset for z
    ; Field offset for z: 16
    add rax, 16       ; Add field offset
    mov rax, [rax]    ; Load field value
    mov rbx, rax     ; Move right operand to RBX
    pop rax            ; Restore left operand
    add rax, rbx      ; + operation
    ; Return value in %rax
    jmp Lmain_exit
Lmain_exit:
    ; Function epilogue
    mov rsp, rbp  ; Restore stack pointer
    ; Restore callee-saved registers
    pop r15          ; Restore callee-saved register
    pop r14          ; Restore callee-saved register
    pop r13          ; Restore callee-saved register
    pop r12          ; Restore callee-saved register
    pop rbx          ; Restore callee-saved register
    pop rbp         ; Restore old base pointer
    ret               ; Return to caller

; Default program entry point
global _start
_start:
    ; Exit gracefully
    mov rax, 60    ; sys_exit
    mov rdi, 0     ; exit status
    syscall
