; Generated by MethASM
; x86-64 Assembly Output

section .text
; Code section

; First pass: processing 1 declarations
; Declaration 0 type: 2 (AST_INLINE_ASM = 10)

global test

test:
    push rbp        ; Save old base pointer
    mov rbp, rsp  ; Set new base pointer
    ; Save callee-saved registers
    push rbx         ; Save callee-saved register
    push r12         ; Save callee-saved register
    push r13         ; Save callee-saved register
    push r14         ; Save callee-saved register
    push r15         ; Save callee-saved register
    ; Registering 0 function parameters
    ; Return statement
    ; Integer literal: 42
    mov rax, 42
    ; Return value in %rax
    jmp Ltest_exit
Ltest_exit:
    ; Function epilogue
    mov rsp, rbp  ; Restore stack pointer
    ; Restore callee-saved registers
    pop r15          ; Restore callee-saved register
    pop r14          ; Restore callee-saved register
    pop r13          ; Restore callee-saved register
    pop r12          ; Restore callee-saved register
    pop rbx          ; Restore callee-saved register
    pop rbp         ; Restore old base pointer
    ret               ; Return to caller

; Default program entry point
global _start
_start:
    ; Exit gracefully
    mov rax, 60    ; sys_exit
    mov rdi, 0     ; exit status
    syscall
