#include "code_generator.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdarg.h>

CodeGenerator* code_generator_create(SymbolTable* symbol_table, RegisterAllocator* allocator) {
    CodeGenerator* generator = malloc(sizeof(CodeGenerator));
    if (!generator) return NULL;
    
    generator->symbol_table = symbol_table;
    generator->register_allocator = allocator;
    generator->output_file = NULL;
    generator->output_buffer = malloc(4096);
    generator->buffer_size = 0;
    generator->buffer_capacity = 4096;
    generator->current_label_id = 0;
    
    if (!generator->output_buffer) {
        free(generator);
        return NULL;
    }
    
    generator->output_buffer[0] = '\0';
    
    return generator;
}

void code_generator_destroy(CodeGenerator* generator) {
    if (generator) {
        free(generator->output_buffer);
        free(generator);
    }
}

int code_generator_generate_program(CodeGenerator* generator, ASTNode* program) {
    // Generate basic assembly header
    (void)program; // Suppress unused parameter warning
    code_generator_emit(generator, ".section .text\n");
    code_generator_emit(generator, ".global _start\n\n");
    code_generator_emit(generator, "_start:\n");
    code_generator_emit(generator, "    # Generated by MethASM\n");
    code_generator_emit(generator, "    # Program stub - no actual implementation yet\n");
    code_generator_emit(generator, "    mov $60, %%rax    # sys_exit\n");
    code_generator_emit(generator, "    mov $0, %%rdi     # exit status\n");
    code_generator_emit(generator, "    syscall\n");
    
    return 1;
}

void code_generator_generate_function(CodeGenerator* generator, ASTNode* function) {
    // Stub implementation
    (void)generator; // Suppress unused parameter warning
    (void)function;  // Suppress unused parameter warning
}

void code_generator_generate_statement(CodeGenerator* generator, ASTNode* statement) {
    // Stub implementation
    (void)generator; // Suppress unused parameter warning
    (void)statement; // Suppress unused parameter warning
}

void code_generator_generate_expression(CodeGenerator* generator, ASTNode* expression) {
    // Stub implementation
    (void)generator;  // Suppress unused parameter warning
    (void)expression; // Suppress unused parameter warning
}

void code_generator_emit(CodeGenerator* generator, const char* format, ...) {
    va_list args;
    va_start(args, format);
    
    // Calculate required size
    va_list args_copy;
    va_copy(args_copy, args);
    int required_size = vsnprintf(NULL, 0, format, args_copy);
    va_end(args_copy);
    
    // Ensure buffer has enough space
    if (generator->buffer_size + required_size + 1 > generator->buffer_capacity) {
        size_t new_capacity = generator->buffer_capacity * 2;
        while (new_capacity < generator->buffer_size + required_size + 1) {
            new_capacity *= 2;
        }
        
        char* new_buffer = realloc(generator->output_buffer, new_capacity);
        if (!new_buffer) {
            va_end(args);
            return;
        }
        
        generator->output_buffer = new_buffer;
        generator->buffer_capacity = new_capacity;
    }
    
    // Append to buffer
    int written = vsnprintf(generator->output_buffer + generator->buffer_size, 
                           generator->buffer_capacity - generator->buffer_size, 
                           format, args);
    
    if (written > 0) {
        generator->buffer_size += written;
    }
    
    va_end(args);
}

char* code_generator_get_output(CodeGenerator* generator) {
    return generator->output_buffer;
}